// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzojc5f8teCWcbWcj401383f0r4YH7ei8',
    appId: '1:536378855239:android:dcf853346ae0f233fd8662',
    messagingSenderId: '536378855239',
    projectId: 'auraly-voice-assistant',
    storageBucket: 'auraly-voice-assistant.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_mOyraAGNjxtG6QmX8JyIcJZnWOXyu4',
    appId: '1:536378855239:ios:8a9dfff862405eaafd8662',
    messagingSenderId: '536378855239',
    projectId: 'auraly-voice-assistant',
    storageBucket: 'auraly-voice-assistant.firebasestorage.app',
    androidClientId: '536378855239-p4j65n1rkbqcf05ogmlfs13jtf55ofba.apps.googleusercontent.com',
    iosClientId: '536378855239-4qkc5viatg6lcgt50a1gfb75l4e2qjvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.voiceAssistant',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC6ONgm3kBgBNrQYWV5q5osZDrK1gei_4',
    appId: '1:536378855239:web:26068299de3a5c89fd8662',
    messagingSenderId: '536378855239',
    projectId: 'auraly-voice-assistant',
    authDomain: 'auraly-voice-assistant.firebaseapp.com',
    storageBucket: 'auraly-voice-assistant.firebasestorage.app',
  );
}
